### ISSUE TITLE
Pagination Hover on Safari

### ISSUE THREAD

**Issue by mttymtt** [arrowtype/blog#20]
The gradient pagination hover is clipping incorrectly on Safari*. (See screenshot below)

It may be best to wrap each older and newer section as the link, and then setting the post titles in span tags similar to how you approached the home page.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/10723688/106278998-bbce0180-6209-11eb-8b05-801955d25ed3.png">

---

*Version 14.0 (15610.1.28.1.9, 15610)

**Comment by arrowtype** [comment]
Good find; thanks for posting about it here!

Good idea on the potential fix. I'll give it a try and update here!

**Comment by arrowtype** [comment]
Doing this in the underline method is a bit fiddly, so I ended up adjusting the styles to more-closely match the homepage list items. It now works well on Safari (and continues to work in Chrome & Firefox):

![image](https://user-images.githubusercontent.com/45946693/106302325-d06cc280-6226-11eb-9d2b-a4183c141257.png)
